export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_STUDENTS = "GET_STUDENTS";

export const GET_FEEDBACKS = "GET_FEEDBACKS";